services:
  plex:
    image: binhex/arch-plexpass:latest
    container_name: binhex-plex
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      # optional: add your Plex claim token in .env
      # - PLEX_CLAIM=${PLEX_CLAIM}
    volumes:
      - /mnt/user/appdata/plex:/config
      - /mnt/user/data:/data
      - /mnt/user/appdata/plex/transcode:/transcode
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    devices:
      - /dev/dri:/dev/dri   # enable HW transcoding (Intel/AMD iGPU)
    networks:
      - dansproxy

networks:
  dansproxy:
    external: true
