services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
    volumes:
      - /mnt/user/appdata/jackett:/config
      - /mnt/user/data:/downloads
    ports:
      - "9117:9117"
    networks:
      - dansproxy

networks:
  dansproxy:
    external: true
