services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=${UMASK}
      - WEBUI_PORT=8080
    volumes:
      - /mnt/user/appdata/qbittorrent:/config
      - /mnt/user/data:/data
    ports:
      - "8080:8080"   # WebUI
      - "6881:6881"   # TCP
      - "6881:6881/udp"
    networks:
      - dansproxy

networks:
  dansproxy:
    external: true
