services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /mnt/user/appdata/tautulli:/config
    ports:
      - "8181:8181"
    networks:
      - dansproxy

networks:
  dansproxy:
    external: true
