services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    command:
      - --path.rootfs=/
    networks:
      - plex_monitoring_default

networks:
  plex_monitoring_default:
    external: true
